export default API_HOST = "https://e9d5-152-0-27-54.ngrok.io" ;
export const ACTION_GET_PRODUCTS = "GET_PRODUCTS"
export const ACTION_GET_PRODUCT = "GET_PRODUCT"
export const ACTION_INSERT_PRODUCT = "INSERT_PRODUCT"
export const ACTION_UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const ACTION_DELETE_PRODUCT = "DELETE_PRODUCT"
export const ACTION_RESET_PRODUCT = "RESET_PRODUCT"
export const ACTION_SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT"
export const ACTION_GET_CURRENT_PRODUCT = "GET_CURRENT_PRODUCT"
export const ACTION_ADD_USER = "ADD_USER"
export const ACTION_CHANGE_USER = "CHANGE_USER"
export const ACTION_CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const ACTION_GET_EXPENSIVE = "GET_EXPENSIVE"
export const ACTION_INSERT_EXPENSIVE = "INSERT_EXPENSIVE"
export const ACTION_UPDATE_EXPENSIVE = "UPDATE_EXPENSIVE"
export const ACTION_DELETE_EXPENSIVE = "DELETE_EXPENSIVE"
export const ACTION_SET_CURRENT_EXPENSIVE = "SET_CURRENT_EXPENSIVE"
export const ACTION_GET_CURRENT_EXPENSIVE = "GET_CURRENT_EXPENSIVE"
export const ACTION_GET_POSTS = "GET_POSTS"
export const ACTION_GET_POST = "GET_POST"
export const ACTION_INSERT_POST = "INSERT_POST"
export const ACTION_UPDATE_POST = "UPDATE_POST"
export const ACTION_DELETE_POST = "DELETE_POST"
export const ACTION_SET_CURRENT_POST = "SET_CURRENT_POST"
export const ACTION_GET_CURRENT_POST = "GET_CURRENT_POST"
export const ACTION_CHANGE_EXPENSIVE = "CHANGE_EXPENSIVE"
export const ACTION_RESET_EXPENSIVE = "RESET_EXPENSIVE"
export const ACTION_CHANGE_EXPENSIVE_FOR_DISPLAY = "CHANGE_EXPENSIVE_FOR_DISPLAY"



























