export default API_HOST = "https://e9d5-152-0-27-54.ngrok.io" ;
export const ACTION_GET_PRODUCTS = "GET_PRODUCTS"
export const ACTION_GET_PRODUCT = "GET_PRODUCT"
export const ACTION_INSERT_PRODUCT = "INSERT_PRODUCT"
export const ACTION_UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const ACTION_DELETE_PRODUCT = "DELETE_PRODUCT"
export const ACTION_RESET_PRODUCT = "RESET_PRODUCT"
export const ACTION_ADD_USER = "ADD_USER"
export const ACTION_CHANGE_USER = "CHANGE_USER"
export const ACTION_CHANGE_PASSWORD = "CHANGE_PASSWORD"







